name: Versioning Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Bump Version
        id: bump
        uses: hugh-nguyen/cortex-cytoskeleton/.github/actions/bump_version@main
        with:
          latest_tag: ${{ needs.get_latest_tag.outputs.latest_tag }}

  tag_commit:
    needs: 
      - bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Tag Commit
        uses: hugh-nguyen/cortex-cytoskeleton/.github/actions/tag_commit@main
        with:
          new_tag: ${{ needs.bump_version.outputs.new_tag }}
          github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
  